export const drawerWidth: number;
export const transition: Record<string, unknown>;
export const container: Record<string, unknown>;
export const containerFluid: Record<string, unknown>;
export const boxShadow: Record<string, unknown>;
export const card: Record<string, unknown>;
export const defaultFontFamily: Record<string, unknown>;
export const defaultFont: Record<string, unknown>;
export const primaryColor: string[];
export const secondaryColor: string[];
export const warningColor: string[];
export const dangerColor: string[];
export const successColor: string[];
export const infoColor: string[];
export const roseColor: string[];
export const grayColor: string[];
export const whiteColor: string;
export const blackColor: string;
export const twitterColor: string;
export const facebookColor: string;
export const googleColor: string;
export const linkedinColor: string;
export const pinterestColor: string;
export const youtubeColor: string;
export const tumblrColor: string;
export const behanceColor: string;
export const dribbbleColor: string;
export const redditColor: string;
export const instagramColor: string;
export const primaryBoxShadow: Record<string, unknown>;
export const infoBoxShadow: Record<string, unknown>;
export const successBoxShadow: Record<string, unknown>;
export const warningBoxShadow: Record<string, unknown>;
export const dangerBoxShadow: Record<string, unknown>;
export const roseBoxShadow: Record<string, unknown>;
export const warningCardHeader: Record<string, unknown>;
export const successCardHeader: Record<string, unknown>;
export const dangerCardHeader: Record<string, unknown>;
export const infoCardHeader: Record<string, unknown>;
export const primaryCardHeader: Record<string, unknown>;
export const roseCardHeader: Record<string, unknown>;
export const cardActions: Record<string, unknown>;
export const cardHeader: Record<string, unknown>;
export const defaultBoxShadow: Record<string, unknown>;
export const title: Record<string, unknown>;
export const cardTitle: Record<string, unknown>;
export const description: Record<string, unknown>;
export const cardLink: Record<string, unknown>;
export const cardSubtitle: Record<string, unknown>;
export const main: Record<string, unknown>;
export const mainRaised: Record<string, unknown>;
export const section: Record<string, unknown>;
export const sectionDark: Record<string, unknown>;
export const sectionDescription: Record<string, unknown>;
export const mlAuto: Record<string, unknown>;
export const mrAuto: Record<string, unknown>;
export const btnLink: Record<string, unknown>;
export const coloredShadow: Record<string, unknown>;
export function hexToRgb(input: string): string;
